import {
  PriceGreen,
  PriceRed,
  PriceViolet,
  PriceOrange,
  Success,
  CheckViolet,
  CheckRed,
  CheckOrange,
} from '@/assets/icons'

export const tariffs = [
  {
    id: 1,
    icon: PriceGreen(),
    title: 'Стартовый',
    price: 290,
    year: 3480,
    check: Success(),
    advantage: ['1 сотрудник', '3 объекта', '100 ТМЦ', '3 клиента'],
    popular: false,
    sale: false,
  },
  {
    id: 2,
    icon: PriceViolet(),
    title: 'Профессиональный',
    price: 390,
    year: 4680,
    check: CheckViolet(),
    advantage: ['2 сотрудника', '6 объектов', '200 ТМЦ', '6 клиентов'],
    popular: false,
    sale: true,
  },
  {
    id: 3,
    icon: PriceOrange(),
    title: 'Оптимальный',
    price: 490,
    year: 5880,
    check: CheckOrange(),
    advantage: ['3 сотрудника', '9 объектов', '300 ТМЦ', '9 клиентов'],
    popular: true,
    sale: false,
  },
  {
    id: 4,
    icon: PriceRed(),
    title: 'Премиальный',
    price: 990,
    year: 11880,
    check: CheckRed(),
    advantage: ['4 сотрудника', '12 объектов', '400 ТМЦ', '12 клиентов'],
    popular: false,
    sale: false,
  },
]
