import React from 'react'
import * as process from 'process'
import Head from 'next/head'
import { Inter } from '@next/font/google'
import Layout from '@/components/Layout/Layout'

import styles from '@/styles/styles.module.scss'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Layout>
          <div className={styles.description}>
            <h1>Главная страница</h1>
            {/*<div>PRIVATE_DB_CONNECT: {process.env.DB_CONNECT}</div>*/}
            <div>PUBLIC_DB_CONNECT: {process.env.NEXT_PUBLIC_DB_CONNECT}</div>
          </div>
        </Layout>
      </main>
    </>
  )
}
